version: '3.8'

services:
  postgres_sinan:
    image: postgres:16
    container_name: postgres_sinan
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sinan_api
    ports:
      - "5433:5432"
    volumes:
      - sinan_pgdata:/var/lib/postgresql/data

volumes:
  sinan_pgdata: